-- Seed data generated from catalog.js / announcements.js
-- Run AFTER schema.sql, in Supabase → SQL Editor.

truncate deals, products, categories restart identity cascade;

insert into categories (id, icon, img, en, bn, ja, sort) values
  ('rice', '', 'assets/img/categories/rice.jpg', 'Rice & Flour', 'চাল ও আটা', '米・粉類', 0),
  ('meat', '', 'assets/img/categories/meat.jpg', 'Meat', 'মাংস', '肉類', 1),
  ('fish', '', 'assets/img/categories/fish.jpg', 'Fish', 'মাছ', '魚類', 2),
  ('lentils', '', 'assets/img/categories/lentils.jpg', 'Lentils & Beans', 'ডাল ও শিম', '豆類', 3),
  ('masala', '', 'assets/img/categories/masala.jpg', 'Masala & Spices', 'মসলা', 'スパイス', 4),
  ('oil', '', 'assets/img/categories/oil.jpg', 'Oil & Ghee', 'তেল ও ঘি', '油・ギー', 5),
  ('snacks', '', 'assets/img/categories/snacks.jpg', 'Snacks & Sweets', 'স্ন্যাকস ও মিষ্টি', 'スナック・お菓子', 6),
  ('dates', '', 'assets/img/categories/dates.jpg', 'Dates & Dry Fruits', 'খেজুর ও বাদাম', 'デーツ・ナッツ', 7),
  ('drinks', '', 'assets/img/categories/drinks.jpg', 'Drinks & Beverage', 'পানীয়', '飲み物', 8),
  ('cosmetics', '', 'assets/img/categories/cosmetics.jpg', 'Cosmetics & Beauty', 'কসমেটিকস ও রূপচর্চা', '化粧品・美容', 9),
  ('others', '', 'assets/img/categories/others.jpg', 'Others', 'অন্যান্য', 'その他', 10);

insert into products (category_id, en, bn, ja, w, p, was, img, tag, sort) values
  ('rice', 'Premium Basmati Rice', 'প্রিমিয়াম বাসমতি চাল', '高級バスマティ米', '5 kg', 3890, 4280, 'assets/img/products/basmati-premium.jpg', null, 0),
  ('rice', 'Thai Rice', 'থাই চাল', 'タイ米', '5 kg', 2990, 3600, 'assets/img/products/thai-rice.jpg', null, 1),
  ('rice', 'Atta Whole Wheat Flour', 'আটা', '全粒粉（アタ）', '5 kg', 1490, 0, 'assets/img/products/atta-flour.jpg', null, 2),
  ('rice', 'Gram Flour (Besan)', 'বেসন', 'ベサン粉', '1 kg', 520, 0, 'assets/img/products/gram-flour.jpg', null, 3),
  ('rice', 'Rice Flour', 'চালের গুঁড়া', '米粉', '1 kg', 420, 0, 'assets/img/products/rice-flour.jpg', null, 4),
  ('meat', 'Chicken Whole Halal', 'আস্ত মুরগি', '丸鶏（ハラール）', '1 kg', 498, 580, 'assets/img/products/chicken-whole.jpg', null, 0),
  ('meat', 'Chicken Boneless Leg', 'হাড় ছাড়া মুরগির রান', '骨なし鶏もも肉', '2 kg', 1180, 1450, 'assets/img/products/chicken-boneless-leg.jpg', null, 1),
  ('meat', 'Chicken Breast Boneless', 'মুরগির বুকের মাংস', '鶏むね肉', '2 kg', 1850, 0, 'assets/img/products/chicken-breast.jpg', null, 2),
  ('meat', 'Chicken Leg with Bone', 'হাড়সহ মুরগির রান', '骨付き鶏もも肉', '2 kg', 1690, 1735, 'assets/img/products/chicken-leg-bone.jpg', null, 3),
  ('meat', 'Beef with Bone', 'হাড়সহ গরুর মাংস', '骨付き牛肉', '1 kg', 1920, 0, 'assets/img/products/beef-bone.jpg', null, 4),
  ('meat', 'Beef Boneless', 'হাড় ছাড়া গরুর মাংস', '牛肉（骨なし）', '1 kg', 2380, 0, 'assets/img/products/beef-boneless.jpg', null, 5),
  ('meat', 'Beef Mince (Keema)', 'গরুর কিমা', '牛ひき肉', '1 kg', 2180, 0, 'assets/img/products/beef-mince.jpg', null, 6),
  ('meat', 'Mutton Curry Cut', 'খাসির মাংস', 'マトン（カレー用）', '1 kg', 3480, 0, 'assets/img/products/mutton.jpg', null, 7),
  ('meat', 'Chicken Liver', 'মুরগির কলিজা', '鶏レバー', '500 g', 580, 0, 'assets/img/products/chicken-liver.jpg', null, 8),
  ('meat', 'Chicken Sausage', 'চিকেন সসেজ', 'チキンソーセージ', '375 g', 350, 395, 'assets/img/products/chicken-sausage.jpg', null, 9),
  ('fish', 'Rohu Fish Whole', 'রুই মাছ', 'ロフ魚', '1 kg', 1290, 0, 'assets/img/products/rohu-fish.jpg', null, 0),
  ('fish', 'Katla Fish Cut', 'কাতলা মাছ', 'カトラ魚', '1 kg', 1390, 0, 'assets/img/products/katla-fish.jpg', null, 1),
  ('fish', 'Tilapia Whole Frozen', 'তেলাপিয়া মাছ', 'ティラピア（冷凍）', '800 g', 398, 440, 'assets/img/products/tilapia.jpg', null, 2),
  ('fish', 'Pangas Fish Fillet', 'পাঙ্গাস ফিলে', 'パンガス フィレ', '1 kg', 980, 0, 'assets/img/products/pangas.jpg', null, 3),
  ('fish', 'Prawn / Shrimp Medium', 'চিংড়ি (মাঝারি)', 'エビ（中）', '500 g', 1480, 0, 'assets/img/products/prawn.jpg', null, 4),
  ('lentils', 'Masoor Dal (Red Lentil)', 'মসুর ডাল', 'レンズ豆（マスール）', '1 kg', 261, 394, 'assets/img/products/masoor-dal.jpg', null, 0),
  ('lentils', 'Red Kidney Beans', 'রাজমা', '赤インゲン豆', '1 kg', 720, 0, 'assets/img/products/kidney-beans.jpg', null, 1),
  ('masala', 'Shan Biryani Masala', 'শান বিরিয়ানি মসলা', 'ビリヤニマサラ', '60 g', 230, 0, 'assets/img/products/biryani-masala.jpg', null, 0),
  ('masala', 'Shan Chicken Masala', 'শান চিকেন মসলা', 'チキンマサラ', '50 g', 210, 0, 'assets/img/products/shan-masala.jpg', null, 1),
  ('masala', 'MDH Garam Masala', 'গরম মসলা', 'ガラムマサラ', '100 g', 390, 0, 'assets/img/products/garam-masala.jpg', null, 2),
  ('oil', 'Sunflower Oil', 'সূর্যমুখী তেল', 'ひまわり油', '1 L', 590, 0, 'assets/img/products/sunflower-oil.jpg', null, 0),
  ('oil', 'Olive Pomace Oil', 'অলিভ অয়েল', 'オリーブオイル', '1 L', 890, 0, 'assets/img/products/olive-oil.jpg', null, 1),
  ('snacks', 'Plain Paratha (5 pcs)', 'পরোটা (৫ পিস)', 'パラタ（5枚）', '400 g', 190, 290, 'assets/img/products/paratha.jpg', null, 0),
  ('snacks', 'Samosa Frozen (10 pcs)', 'সমুচা (১০ পিস)', 'サモサ（冷凍10個）', '500 g', 680, 0, 'assets/img/products/samosa.jpg', null, 1),
  ('snacks', 'Wai Wai Noodles', 'ওয়াই ওয়াই নুডলস', 'ワイワイヌードル', '60 g', 59, 101, 'assets/img/products/waiwai-noodles.jpg', null, 2),
  ('snacks', 'Indomie Instant Noodles', 'ইন্দোমি নুডলস', 'インドミー', '67 g', 120, 140, 'assets/img/products/indomie.jpg', null, 3),
  ('snacks', 'Haldiram Namkeen Mix', 'হালদিরাম নমকিন', 'ナムキン ミックス', '200 g', 390, 0, 'assets/img/products/haldiram-namkeen.jpg', null, 4),
  ('snacks', 'Milk Cookies', 'মিল্ক কুকিজ', 'ミルククッキー', '900 g', 670, 0, 'assets/img/products/milk-cookies.jpg', null, 5),
  ('snacks', 'Butter Cookies', 'বাটার কুকিজ', 'バタークッキー', '900 g', 670, 0, 'assets/img/products/butter-cookies.jpg', null, 6),
  ('snacks', 'Jackfruit Chips', 'কাঁঠাল চিপস', 'ジャックフルーツチップス', '100 g', 398, 0, 'assets/img/products/jackfruit-chips.jpg', null, 7),
  ('dates', 'Regular Dates', 'সাধারণ খেজুর', 'デーツ', '500 g', 680, 0, 'assets/img/products/dates-regular.jpg', null, 0),
  ('drinks', 'Mango Fruit Drink', 'ম্যাঙ্গো জুস', 'マンゴージュース', '1 L', 280, 0, 'assets/img/products/mango-drink-1l.jpg', null, 0),
  ('drinks', 'Mango Fruit Drink', 'ম্যাঙ্গো জুস', 'マンゴージュース', '2 L', 550, 0, 'assets/img/products/mango-drink-2l.jpg', null, 1),
  ('drinks', 'Guava Fruit Drink', 'পেয়ারা জুস', 'グアバジュース', '1 L', 280, 0, 'assets/img/products/guava-drink-1l.jpg', null, 2),
  ('drinks', 'Pomegranate Drink', 'ডালিম জুস', 'ザクロジュース', '1 L', 280, 0, 'assets/img/products/pomegranate-1l.jpg', null, 3),
  ('drinks', 'Powder Milk', 'গুঁড়া দুধ', '粉ミルク', '1 kg', 1980, 0, 'assets/img/products/powder-milk.jpg', null, 4),
  ('cosmetics', 'Himalaya Day Cream', 'হিমালয়া ডে ক্রিম', 'ヒマラヤ デイクリーム', '50 ml', 1290, 0, 'assets/img/products/cream-himalaya.jpg', null, 0),
  ('cosmetics', 'Halal Body Shampoo', 'হালাল বডি শ্যাম্পু', 'ハラール ボディシャンプー', '400 ml', 980, 0, 'assets/img/products/shampoo.jpg', null, 1),
  ('cosmetics', 'Deodorant Roll-On', 'ডিওডোরেন্ট', 'デオドラント', '50 ml', 590, 0, 'assets/img/products/deodorant.jpg', null, 2),
  ('cosmetics', 'Body Spray', 'বডি স্প্রে', 'ボディスプレー', '59 g', 780, 0, 'assets/img/products/body-spray.jpg', null, 3),
  ('others', 'Mixed Pickle', 'মিক্সড আচার', 'ミックスピクルス', '400 g', 590, 0, 'assets/img/products/pickle.jpg', null, 0),
  ('others', 'Honey Pure', 'খাঁটি মধু', '純粋はちみつ', '500 g', 1480, 0, 'assets/img/products/honey.jpg', null, 1);

insert into deals (type, en, bn, ja, w, p, was, img, sort) values
  ('new', 'Beef with Bone', 'হাড়সহ গরুর মাংস', '骨付き牛肉', '1 kg', 1920, 2180, 'assets/img/products/beef-bone.jpg', 0),
  ('deal', 'Tilapia Whole Frozen', 'তেলাপিয়া মাছ', 'ティラピア（冷凍）', '800 g', 398, 440, 'assets/img/products/tilapia.jpg', 1),
  ('new', 'Mutton Curry Cut', 'খাসির মাংস', 'マトン（カレー用）', '1 kg', 3480, 0, 'assets/img/products/mutton.jpg', 2),
  ('new', 'Prawn / Shrimp Medium', 'চিংড়ি (মাঝারি)', 'エビ（中）', '500 g', 1480, 0, 'assets/img/products/prawn.jpg', 3),
  ('deal', 'Masoor Dal (Red Lentil)', 'মসুর ডাল', 'レンズ豆（マスール）', '1 kg', 261, 394, 'assets/img/products/masoor-dal.jpg', 4),
  ('deal', 'Premium Basmati Rice', 'প্রিমিয়াম বাসমতি চাল', '高級バスマティ米', '5 kg', 3690, 4280, 'assets/img/products/basmati-premium.jpg', 5);
